### ISSUE TITLE
`mtenv setup` fails when a symlink to another install already exists

### ISSUE THREAD

**Issue by badBlackShark** [myst-lang/mtenv#1]
I tried to set up mtenv on an Ubuntu machine, and ran into a problem:
I cloned the repo, compiled it with `shards build`, and moved the binary onto my $PATH, which all worked fine.

When I ran `mtenv setup` though, I got this error:
![error](https://user-images.githubusercontent.com/25396986/38399547-565f9d16-394b-11e8-9a8d-db4afba558d5.png)

**Comment by faultyserver** [comment]
It looks like you already have a `myst` symlink in `/usr/local/bin` that's pointing to some other Myst installation that isn't managed by `mtenv` (and also apparently doesn't exist, which is why it's red).

If you remove that symlink (`rm /usr/local/bin/myst`), then run `mtenv setup` again, it should succeed.

I actually specifically remember when I was writing the `setup` command that I thought "no one will ever hit this corner-case", so I didn't handle it........woops. It checks to see if the File is a regular File or doesn't exist at all, but doesn't handle where the File exists as a symlink.

To make sure people don't hit this in the future, the `setup` command should check to make sure that if a `myst` filex already exists as a symlink, it points to the location that `mtenv` expects (e.g. `~/.mtenv/shims/myst`). If it points somewhere else, it should complain and tell the user to remove the existing symlink. I don't want to forceably remove the file without the user knowing what happened.

**Comment by faultyserver** [comment]
Should be fixed by #4
